export type Ingredient = {
  name: string;
  image: string;
  isVegetarian: boolean;
  isBreakfast: boolean;
  isDinner: boolean;
};

export const ingredients: Record<string, Ingredient[]> = {
  rice: [
    {
      name: "brown rice",
      image: "/src/assets/images/ingredients/rice/brown-rice.png",
      isVegetarian: true,
      isBreakfast: false,
      isDinner: true,
    },
    {
      name: "white rice",
      image: "/src/assets/images/ingredients/rice/white-rice.png",
      isVegetarian: true,
      isBreakfast: false,
      isDinner: true,
    },
  ],
  beans: [
    {
      name: "black beans",
      image: "/src/assets/images/ingredients/beans/black-beans.png",
      isVegetarian: true,
      isBreakfast: false,
      isDinner: true,
    },
    {
      name: "pinto beans",
      image: "/src/assets/images/ingredients/beans/pinto-beans.png",
      isVegetarian: true,
      isBreakfast: false,
      isDinner: true,
    },
  ],
  protein: [
    {
      name: "bacon",
      image: "/src/assets/images/ingredients/protein/bacon.png",
      isVegetarian: false,
      isBreakfast: true,
      isDinner: false,
    },
    {
      name: "brisket",
      image: "/src/assets/images/ingredients/protein/brisket.png",
      isVegetarian: false,
      isBreakfast: false,
      isDinner: true,
    },
    {
      name: "chicken tenders",
      image: "/src/assets/images/ingredients/protein/chicken-tenders.png",
      isVegetarian: false,
      isBreakfast: false,
      isDinner: true,
    },
    {
      name: "chorizo",
      image: "/src/assets/images/ingredients/protein/chorizo.png",
      isVegetarian: false,
      isBreakfast: true,
      isDinner: false,
    },
    {
      name: "grilled chicken",
      image: "/src/assets/images/ingredients/protein/grilled-chicken.png",
      isVegetarian: false,
      isBreakfast: false,
      isDinner: true,
    },
    {
      name: "ground beef",
      image: "/src/assets/images/ingredients/protein/ground-beef.png",
      isVegetarian: false,
      isBreakfast: false,
      isDinner: true,
    },
    {
      name: "pork",
      image: "/src/assets/images/protein/ingredients/pork.png",
      isVegetarian: false,
      isBreakfast: false,
      isDinner: true,
    },
    {
      name: "sauteed vegetables",
      image: "/src/assets/images/ingredients/protein/sauteed-vegetables.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
    {
      name: "shitake mushroom",
      image: "/src/assets/images/ingredients/protein/shitake-mushroom",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
  ],
  addition: [
    {
      name: "cheese",
      image: "/src/assets/images/ingredients/addition/cheese.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
    {
      name: "coriander",
      image: "/src/assets/images/ingredients/addition/coriander.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
    {
      name: "crushed corn chips",
      image: "/src/assets/images/ingredients/addition/crushed-corn-chips.png",
      isVegetarian: true,
      isBreakfast: false,
      isDinner: true,
    },
    {
      name: "diced onions",
      image: "/src/assets/images/ingredients/addition/diced-onions.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
    {
      name: "fresh jalapenos",
      image: "/src/assets/images/ingredients/addition/fresh-jalapenos.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
    {
      name: "guacamole",
      image: "/src/assets/images/ingredients/addition/guacamole.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
    {
      name: "a hash brown",
      image: "/src/assets/images/ingredients/addition/hash-brown.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: false,
    },
    {
      name: "lettuce",
      image: "/src/assets/images/ingredients/addition/lettuce.png",
      isVegetarian: true,
      isBreakfast: false,
      isDinner: true,
    },
    {
      name: "pico",
      image: "/src/assets/images/ingredients/addition/pico.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
    {
      name: "pickled jalapenos",
      image: "/src/assets/images/ingredients/addition/pickled-jalapenos.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
    {
      name: "queso",
      image: "/src/assets/images/ingredients/addition/queso.png",
      isVegetarian: true,
      isBreakfast: false,
      isDinner: true,
    },
    {
      name: "scrambled eggs",
      image: "/src/assets/images/ingredients/addition/scrambled-eggs.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: false,
    },
    {
      name: "seasoned corn",
      image: "/src/assets/images/ingredients/addition/seasoned-corn",
      isVegetarian: true,
      isBreakfast: false,
      isDinner: true,
    },
  ],
  sauce: [
    {
      name: "chipotle mayo",
      image: "/src/assets/images/ingredients/sauce/chipotle-mayo.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
    {
      name: "habanero salsa",
      image: "/src/assets/images/ingredients/sauce/habanero-salsa.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
    {
      name: "herb mayo",
      image: "/src/assets/images/ingredients/sauce/herb-mayo.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
    {
      name: "jalapeno ketchup",
      image: "/src/assets/images/ingredients/sauce/jalapeno-ketchup.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
    {
      name: "ketchup",
      image: "/src/assets/images/ingredients/sauce/ketchup.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
    {
      name: "roasted jalapeno salsa",
      image: "/src/assets/images/ingredients/sauce/roasted-jalapeno-salsa.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
    {
      name: "smokey chipotle salsa",
      image: "/src/assets/images/ingredients/sauce/smokey-chipotle-salsa.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
    {
      name: "sour cream",
      image: "/src/assets/images/ingredients/sauce/sour-cream.png",
      isVegetarian: true,
      isBreakfast: true,
      isDinner: true,
    },
    {
      name: "tomatillo salsa",
      image: "/src/assets/images/ingredients/sauce/tomatillo-salsa.png",
      isVegetarian: true,
      isBreakfast: false,
      isDinner: true,
    },
  ],
};
